//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA_DE_PAGO
    {
        public decimal NRO_BOLETA { get; set; }
        public System.DateTime HORA_PAGO { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public decimal ID_METODO { get; set; }
        public decimal ID_DETALLE_PEDIDO { get; set; }
    
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        public virtual DETALLE_PEDIDO DETALLE_PEDIDO { get; set; }
    }
}
