//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.PEDIDOS = new HashSet<PEDIDOS>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_CLIENTE { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_USUARIO { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<PEDIDOS> PEDIDOS { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
