//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public DETALLE_PEDIDO()
        {
            this.BOLETA_DE_PAGO = new HashSet<BOLETA_DE_PAGO>();
        }
    
        public decimal NRO_PEDIDO { get; set; }
        public decimal CANT_PEDIDOS { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ID_PLATO { get; set; }
        public decimal ID_DETALLE_PEDIDO { get; set; }
    
        public virtual ICollection<BOLETA_DE_PAGO> BOLETA_DE_PAGO { get; set; }
        public virtual PEDIDOS PEDIDOS { get; set; }
        public virtual PLATO PLATO { get; set; }
    }
}
