//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurante
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO
    {
        public PLATO()
        {
            this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();
            this.STOCK = new HashSet<STOCK>();
        }
    
        public decimal ID_PLATO { get; set; }
        public string NOM_PLATO { get; set; }
        public byte[] IMAGEN { get; set; }
        public decimal PRECIO_PLATO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual ICollection<STOCK> STOCK { get; set; }
    }
}
